scheduler:
  serviceAccountName: platform-scheduler-sa
  image:
    repository: bitnami/kubectl
    tag: "latest"
    pullPolicy: IfNotPresent

platformSchedule:
  enabled: false
  timezone: ""
  start: ""
  end: ""
  dependencies:
    enabled: false
    apps: []
  applications:
    enabled: false
    namespaces: []
