scheduler:
  serviceAccountName: platform-scheduler-sa
  image:
    repository: bitnami/kubectl
    tag: "latest"
    pullPolicy: IfNotPresent
  namespace:
    create: false
    labels:
      config.linkerd.io/admission-webhooks: disabled

platformSchedule:
  timezone: ""
  start: ""
  end: ""
  dependencies:
    enabled: false
    apps: []
  applications:
    enabled: false
    namespaces: []
